# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos_pb2_pb2 as protos__pb2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos.proto',
  package='remote',
  syntax='proto3',
  serialized_pb=_b('\n\x0cprotos.proto\x12\x06remote\x1a\x10protos_pb2.proto\"d\n\x0cMessageBatch\x12\x12\n\ntype_names\x18\x01 \x03(\t\x12\x14\n\x0ctarget_names\x18\x02 \x03(\t\x12*\n\tenvelopes\x18\x03 \x03(\x0b\x32\x17.remote.MessageEnvelope\"{\n\x0fMessageEnvelope\x12\x0f\n\x07type_id\x18\x01 \x01(\x05\x12\x14\n\x0cmessage_data\x18\x02 \x01(\x0c\x12\x0e\n\x06target\x18\x03 \x01(\x05\x12\x1a\n\x06sender\x18\x04 \x01(\x0b\x32\n.actor.PID\x12\x15\n\rserializer_id\x18\x05 \x01(\x05\"-\n\x0f\x41\x63torPidRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\"+\n\x10\x41\x63torPidResponse\x12\x17\n\x03pid\x18\x01 \x01(\x0b\x32\n.actor.PID\"\x06\n\x04Unit\"\x10\n\x0e\x43onnectRequest\"0\n\x0f\x43onnectResponse\x12\x1d\n\x15\x64\x65\x66\x61ult_serializer_id\x18\x01 \x01(\x05\x32}\n\x08Remoting\x12<\n\x07\x43onnect\x12\x16.remote.ConnectRequest\x1a\x17.remote.ConnectResponse\"\x00\x12\x33\n\x07Receive\x12\x14.remote.MessageBatch\x1a\x0c.remote.Unit\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[protos__pb2__pb2.DESCRIPTOR,])




_MESSAGEBATCH = _descriptor.Descriptor(
  name='MessageBatch',
  full_name='remote.MessageBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_names', full_name='remote.MessageBatch.type_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_names', full_name='remote.MessageBatch.target_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='envelopes', full_name='remote.MessageBatch.envelopes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=142,
)


_MESSAGEENVELOPE = _descriptor.Descriptor(
  name='MessageEnvelope',
  full_name='remote.MessageEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_id', full_name='remote.MessageEnvelope.type_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_data', full_name='remote.MessageEnvelope.message_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='remote.MessageEnvelope.target', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender', full_name='remote.MessageEnvelope.sender', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serializer_id', full_name='remote.MessageEnvelope.serializer_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=267,
)


_ACTORPIDREQUEST = _descriptor.Descriptor(
  name='ActorPidRequest',
  full_name='remote.ActorPidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='remote.ActorPidRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kind', full_name='remote.ActorPidRequest.kind', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=314,
)


_ACTORPIDRESPONSE = _descriptor.Descriptor(
  name='ActorPidResponse',
  full_name='remote.ActorPidResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='remote.ActorPidResponse.pid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=359,
)


_UNIT = _descriptor.Descriptor(
  name='Unit',
  full_name='remote.Unit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=367,
)


_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='remote.ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=385,
)


_CONNECTRESPONSE = _descriptor.Descriptor(
  name='ConnectResponse',
  full_name='remote.ConnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='default_serializer_id', full_name='remote.ConnectResponse.default_serializer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=435,
)

_MESSAGEBATCH.fields_by_name['envelopes'].message_type = _MESSAGEENVELOPE
_MESSAGEENVELOPE.fields_by_name['sender'].message_type = protos__pb2__pb2._PID
_ACTORPIDRESPONSE.fields_by_name['pid'].message_type = protos__pb2__pb2._PID
DESCRIPTOR.message_types_by_name['MessageBatch'] = _MESSAGEBATCH
DESCRIPTOR.message_types_by_name['MessageEnvelope'] = _MESSAGEENVELOPE
DESCRIPTOR.message_types_by_name['ActorPidRequest'] = _ACTORPIDREQUEST
DESCRIPTOR.message_types_by_name['ActorPidResponse'] = _ACTORPIDRESPONSE
DESCRIPTOR.message_types_by_name['Unit'] = _UNIT
DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectResponse'] = _CONNECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageBatch = _reflection.GeneratedProtocolMessageType('MessageBatch', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEBATCH,
  __module__ = 'protos_pb2'
  # @@protoc_insertion_point(class_scope:remote.MessageBatch)
  ))
_sym_db.RegisterMessage(MessageBatch)

MessageEnvelope = _reflection.GeneratedProtocolMessageType('MessageEnvelope', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEENVELOPE,
  __module__ = 'protos_pb2'
  # @@protoc_insertion_point(class_scope:remote.MessageEnvelope)
  ))
_sym_db.RegisterMessage(MessageEnvelope)

ActorPidRequest = _reflection.GeneratedProtocolMessageType('ActorPidRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACTORPIDREQUEST,
  __module__ = 'protos_pb2'
  # @@protoc_insertion_point(class_scope:remote.ActorPidRequest)
  ))
_sym_db.RegisterMessage(ActorPidRequest)

ActorPidResponse = _reflection.GeneratedProtocolMessageType('ActorPidResponse', (_message.Message,), dict(
  DESCRIPTOR = _ACTORPIDRESPONSE,
  __module__ = 'protos_pb2'
  # @@protoc_insertion_point(class_scope:remote.ActorPidResponse)
  ))
_sym_db.RegisterMessage(ActorPidResponse)

Unit = _reflection.GeneratedProtocolMessageType('Unit', (_message.Message,), dict(
  DESCRIPTOR = _UNIT,
  __module__ = 'protos_pb2'
  # @@protoc_insertion_point(class_scope:remote.Unit)
  ))
_sym_db.RegisterMessage(Unit)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTREQUEST,
  __module__ = 'protos_pb2'
  # @@protoc_insertion_point(class_scope:remote.ConnectRequest)
  ))
_sym_db.RegisterMessage(ConnectRequest)

ConnectResponse = _reflection.GeneratedProtocolMessageType('ConnectResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTRESPONSE,
  __module__ = 'protos_pb2'
  # @@protoc_insertion_point(class_scope:remote.ConnectResponse)
  ))
_sym_db.RegisterMessage(ConnectResponse)



_REMOTING = _descriptor.ServiceDescriptor(
  name='Remoting',
  full_name='remote.Remoting',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=437,
  serialized_end=562,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='remote.Remoting.Connect',
    index=0,
    containing_service=None,
    input_type=_CONNECTREQUEST,
    output_type=_CONNECTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Receive',
    full_name='remote.Remoting.Receive',
    index=1,
    containing_service=None,
    input_type=_MESSAGEBATCH,
    output_type=_UNIT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTING)

DESCRIPTOR.services_by_name['Remoting'] = _REMOTING

# @@protoc_insertion_point(module_scope)
